services:
  landing1:
    build: ./landing1
    image: landing1:1.0
    container_name: landing1-container
    restart: unless-stopped
    networks:
      - web

  landing2:
    build: ./landing2
    image: landing2:1.0
    container_name: landing2-container
    restart: unless-stopped
    networks:
      - web

  proxy:
    image: nginx:alpine
    container_name: proxy-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - landing1
      - landing2
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"
    networks:
      - web

networks:
  web:
    driver: bridge


