name: Desplegar en el servidor

on:
  push:
    branches:
      - main

jobs:
  desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar al servidor y actualizar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/landingsDocker
            git pull origin main
            docker compose up -d --build
            docker compose ps
